excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://alvinchanmanlung97.github.io
title: alvinchanmanlung97
tagline: A log of everyday life
description: My awesome new site
paginate: 5